### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by eileenfan** [janoliver/pOT-Droid#287]
//package name: com.mde.potdroid
//version: 5.0.6
 java.lang.NullPointerException
 	at com.mde.potdroid.fragments.j$3$1.onClick(SourceFile:245)
 	at android.support.design.widget.Snackbar$3.onClick(SourceFile:306)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View$PerformClick.run(View.java:17721)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by janoliver** [comment]
Ein bisschen Kontext wäre hiflreich. Wo tritt der Fehler auf, welche Android Version, etc.
